-- MySQL Script generated by MySQL Workbench
-- Seg 05 Jun 2017 03:04:52 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema salvamaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema salvamaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `salvamaria` DEFAULT CHARACTER SET utf8 ;
USE `salvamaria` ;

-- -----------------------------------------------------
-- Placeholder table for view `salvamaria`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salvamaria`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `salvamaria`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `salvamaria`.`view1`;
USE `salvamaria`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;