-- MySQL Script generated by MySQL Workbench
-- Seg 03 Jul 2017 01:22:05 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema salvamaria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema salvamaria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `salvamaria` DEFAULT CHARACTER SET utf8 ;
USE `salvamaria` ;

-- -----------------------------------------------------
-- Table `salvamaria`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salvamaria`.`users` (
  `id` VARCHAR(45) NOT NULL,
  `login` INT NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `nivel` ENUM('PM', 'AP', 'USER') NOT NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NOT NULL,
  `pm_responsavel` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salvamaria`.`certidoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salvamaria`.`certidoes` (
  `id` INT NOT NULL,
  `tipo` ENUM('FISCALIZACAO', 'RECUSA', 'RETORNO', 'TERMINO', 'NEGATIVA_ENDERECO') NOT NULL,
  `data` DATETIME NOT NULL,
  `testemunha` VARCHAR(100) NOT NULL,
  `depoimento_usuaria` MEDIUMTEXT NOT NULL,
  `depoimento_agressor` MEDIUMTEXT NULL,
  `createdAt` DATE NULL,
  `updatedAt` DATE NULL,
  `users_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_certidoes_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_certidoes_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `salvamaria`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `salvamaria`.`dailies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salvamaria`.`dailies` (
  `id` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `descricao` MEDIUMTEXT NULL,
  `users_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_dailies_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_dailies_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `salvamaria`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salvamaria`.`contacts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salvamaria`.`contacts` (
  `id` INT NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  `tipo` ENUM('F', 'R', 'O') NOT NULL,
  `createdAt` DATE NOT NULL,
  `updatedAt` DATE NOT NULL,
  `users_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_contacts_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_contacts_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `salvamaria`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salvamaria`.`socioforms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salvamaria`.`socioforms` (
  `id` INT NOT NULL,
  `estado_civil` VARCHAR(45) NOT NULL,
  `filhos` VARCHAR(45) NOT NULL,
  `filhos_com_agressor` VARCHAR(45) NULL,
  `escolaridade` VARCHAR(45) NOT NULL,
  `etnia` VARCHAR(45) NOT NULL,
  `idade` INT NULL,
  `religiao` VARCHAR(45) NULL,
  `profissao` VARCHAR(45) NULL,
  `trabalha` VARCHAR(45) NOT NULL,
  `ultimo_emprego` VARCHAR(45) NULL,
  `local_trabalho` VARCHAR(45) NULL,
  `renda` VARCHAR(45) NOT NULL,
  `responsavel_sustento` VARCHAR(45) NULL,
  `createdAt` DATE NULL,
  `updatedAt` DATE NULL,
  `users_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_socioforms_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_socioforms_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `salvamaria`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `salvamaria`.`addresses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salvamaria`.`addresses` (
  `id` INT NOT NULL,
  `numero` INT NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `complemento` VARCHAR(127) NULL,
  `ponto_referencia` VARCHAR(255) NULL,
  `cep` VARCHAR(10) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `createdAt` DATE NULL,
  `updatedAt` DATE NULL,
  `users_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `users_id`),
  INDEX `fk_addresses_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_addresses_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `salvamaria`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `salvamaria` ;

-- -----------------------------------------------------
-- Placeholder table for view `salvamaria`.`view1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `salvamaria`.`view1` (`id` INT);

-- -----------------------------------------------------
-- View `salvamaria`.`view1`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `salvamaria`.`view1`;
USE `salvamaria`;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
